version: 2
jobs:
  build:
    docker:
      - image: gcr.io/google-appengine/aspnetcore:2.1

    environment:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - run:
          command: |
              echo "Hello CircleCI"
